#端口配置
#解决netstat -ano | findstr 8080  ---->  taskkill -pid 8080 -f
server:
  port: 8181

spring:
  main:
    banner-mode: off   #修改banner
  datasource:
    druid:            #数据库信息
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fictionwebdata
      username: fictionwebdata
      #username: root
      password: xyj18105857856
#日志
logging:
  level:
    root: info

#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   #开启驼峰命名功能

mconfig:
  swagger-ui-open: true  #是否开启swagger接口文档
